workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build React app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS app
        script: xcodebuild -workspace ios/App/App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/ios_archive/App.xcarchive
    artifacts:
      - $CM_BUILD_DIR/ios_archive/*.xcarchive
      - build/ios/ipa/*.ipa
