workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      node: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          # Use npm ci for faster, reliable installs in CI
          npm ci
          # Install Capacitor CLI globally to ensure it's available
          npm install -g @capacitor/cli
      
      - name: Verify installations
        script: |
          # Verify Node and npm versions
          node --version
          npm --version
          # Verify Capacitor CLI is available
          npx cap --version
          # List installed packages to debug dependency issues
          npm list --depth=0
      
      - name: Build React app
        script: |
          # Build the React application
          npm run build
          # Verify build output exists
          ls -la build/ || ls -la dist/
      
      - name: Initialize and Sync Capacitor
        script: |
          # Check if Capacitor is initialized, if not initialize it
          if [ ! -f "capacitor.config.json" ] && [ ! -f "capacitor.config.ts" ]; then
            echo "Initializing Capacitor..."
            npx cap init "aarati-vandan-sutra1-3072025" "com.aarati.vandansutra" --web-dir=build
          fi
          
          # Ensure iOS platform is installed
          npm install @capacitor/ios
          
          # Add iOS platform (this will create the ios folder structure)
          npx cap add ios
          
          # Copy web assets and sync
          npx cap copy ios
          npx cap sync ios
          
          # Verify iOS project structure was created
          ls -la ios/App/ || (echo "iOS platform creation failed" && exit 1)
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $CM_BUILD_DIR/ios_archive/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO
    
    artifacts:
      - $CM_BUILD_DIR/ios_archive/*.xcarchive
      - build/ios/ipa/*.ipa
      - ios/App/build/Build/Products/Release-iphoneos/*.app
